In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
X = df.drop('species', axis=1)
Y = df['species']

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [5]:
from sklearn.svm import SVC

model_SVM = SVC(gamma='auto')

model_SVM.fit(X_train,y_train)

SVC(gamma='auto')

In [6]:
model_SVM.score(X_test,y_test)

1.0

In [7]:
from sklearn.model_selection import GridSearchCV

classifier = GridSearchCV(model_SVM,{
    'C':[1,10,20,30],
    'kernel':['linear','rbf'],
},cv=5,return_train_score=False)

In [8]:
classifier.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['linear', 'rbf']})

In [9]:
classifier.cv_results_

{'mean_fit_time': array([0.01522331, 0.01130672, 0.01061268, 0.01407542, 0.02057781,
        0.01305156, 0.024471  , 0.01128602]),
 'std_fit_time': array([0.0044181 , 0.0027637 , 0.00192734, 0.00445698, 0.00908006,
        0.00251943, 0.0091407 , 0.00317414]),
 'mean_score_time': array([0.01011839, 0.0114439 , 0.01116996, 0.01182413, 0.01771116,
        0.01359286, 0.02036815, 0.00863223]),
 'std_score_time': array([0.0011972 , 0.00192747, 0.00587475, 0.00228064, 0.01475604,
        0.00900574, 0.00649922, 0.00164507]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'}],
 'split0_test_score': array([1.  , 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.9 , 0.9 , 0.85, 0.8 , 0.85, 0.8 , 0.85, 0.8 ]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 1.  , 1.  , 0.95, 1.  , 1.  , 1.  ]),
 'split4_test_score': array([0.95, 0.95, 0.95, 1.  , 1.  , 0.95, 1.  , 1.  ]),
 'mean_test_score': array([0.95, 0.94, 0.93, 0.93, 0.93, 0.92, 0.94, 0.93]),
 'std_test_score': array([0.04472136, 0.03741657, 0.0509902 , 0.07483315, 0.0509902 ,
        0.0678233 , 0.05830952, 0.07483315]),
 'rank_test_score': array([1, 2, 6, 4, 6, 8, 3, 4], dtype=int32)}

In [10]:
result = pd.DataFrame(classifier.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015223,0.004418,0.010118,0.001197,1,linear,"{'C': 1, 'kernel': 'linear'}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
1,0.011307,0.002764,0.011444,0.001927,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,2
2,0.010613,0.001927,0.011170,0.005875,10,linear,"{'C': 10, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,6
3,0.014075,0.004457,0.011824,0.002281,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4
4,0.020578,0.009080,0.017711,0.014756,20,linear,"{'C': 20, 'kernel': 'linear'}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,6
5,0.013052,0.002519,0.013593,0.009006,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,0.95,0.92,0.067823,8
6,0.024471,0.009141,0.020368,0.006499,30,linear,"{'C': 30, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,3
7,0.011286,0.003174,0.008632,0.001645,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4

In [11]:
result[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear             0.95
1        1          rbf             0.94
2       10       linear             0.93
3       10          rbf             0.93
4       20       linear             0.93
5       20          rbf             0.92
6       30       linear             0.94
7       30          rbf             0.93

In [16]:
from sklearn.neighbors import KNeighborsClassifier

model_KNN = KNeighborsClassifier(n_neighbors=9)

params = {
    "n_neighbors": [3, 5, 7, 9, 11],
    "weights": ["uniform", "distance"],
    "p": [1, 2]
}

grid = GridSearchCV(model_KNN,params,cv=5,return_train_score=False)

In [17]:
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=9),
             param_grid={'n_neighbors': [3, 5, 7, 9, 11], 'p': [1, 2],
                         'weights': ['uniform', 'distance']})

In [23]:
result_KNN = pd.DataFrame(grid.cv_results_)
result_KNN

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008702,0.001197,0.012208,0.001424,3,1,uniform,"{'n_neighbors': 3, 'p': 1, 'weights': 'uniform'}",1.00,0.80,0.9,1.0,0.95,0.93,0.074833,7
1,0.007495,0.001174,0.007338,0.002138,3,1,distance,"{'n_neighbors': 3, 'p': 1, 'weights': 'distance'}",1.00,0.80,0.9,1.0,0.95,0.93,0.074833,7
2,0.006104,0.001354,0.008466,0.002499,3,2,uniform,"{'n_neighbors': 3, 'p': 2, 'weights': 'uniform'}",0.95,0.85,0.9,1.0,0.95,0.93,0.050990,14
3,0.005417,0.000925,0.005309,0.001547,3,2,distance,"{'n_neighbors': 3, 'p': 2, 'weights': 'distance'}",1.00,0.85,0.9,1.0,0.95,0.94,0.058310,1
4,0.008205,0.002240,0.008475,0.002868,5,1,uniform,"{'n_neighbors': 5, 'p': 1, 'weights': 'uniform'}",0.95,0.80,0.9,1.0,0.95,0.92,0.067823,17
5,0.007564,0.001666,0.008842,0.003184,5,1,distance,"{'n_neighbors': 5, 'p': 1, 'weights': 'distance'}",0.95,0.80,0.9,1.0,0.95,0.92,0.067823,17
6,0.005474,0.001820,0.007019,0.001846,5,2,uniform,"{'n_neighbors': 5, 'p': 2, 'weights': 'uniform'}",0.90,0.90,0.9,1.0,0.95,0.93,0.040000,7
7,0.004646,0.001143,0.005724,0.001444,5,2,distance,"{'n_neighbors': 5, 'p': 2, 'weights': 'distance'}",0.95,0.90,0.9,1.0,0.95,0.94,0.037417,1
8,0.006179,0.001104,0.007716,0.001334,7,1,uniform,"{'n_neighbors': 7, 'p': 1, 'weights': 'uniform'}",0.95,0.80,0.9,1.0,0.95,0.92,0.067823,17
9,0.004896,0.001049,0.005718,0.001172,7,1,distance,"{'n_neighbors': 7, 'p': 1, 'weights': 'distance'}",0.95,0.80,0.9,1.0,0.95,0.92,0.067823,17
10,0.005118,0.001194,0.007884,0.000813,7,2,uniform,"{'n_neighbors': 7, 'p': 2, 'weights': 'uniform'}",0.90,0.90,0.9,1.0,0.95,0.93,0.040000,7
11,0.006149,0.001361,0.005057,0.001046,7,2,distance,"{'n_neighbors': 7, 'p': 2, 'weights': 'distance'}",0.95,0.90,0.9,1.0,0.95,0.94,0.037417,1
12,0.006052,0.001930,0.007678,0.001247,9,1,uniform,"{'n_neighbors': 9, 'p': 1, 'weights': 'uniform'}",0.95,0.90,0.9,1.0,0.95,0.94,0.037417,1
13,0.005554,0.001085,0.005451,0.001500,9,1,distance,"{'n_neighbors': 9, 'p': 1, 'weights': 'distance'}",0.95,0.85,0.9,1.0,0.95,0.93,0.050990,14
14,0.004876,0.001382,0.005806,0.000456,9,2,uniform,"{'n_neighbors': 9, 'p': 2, 'weights': 'uniform'}",0.90,0.90,0.9,1.0,0.95,0.93,0.040000,7
15,0.006235,0.002547,0.006377,0.001585,9,2,distance,"{'n_neighbors': 9, 'p': 2, 'weights': 'distance'}",0.95,0.90,0.9,1.0,0.95,0.94,0.037417,1
16,0.007518,0.002370,0.006587,0.001445,11,1,uniform,"{'n_neighbors': 11, 'p': 1, 'weights': 'uniform'}",0.95,0.90,0.9,1.0,0.95,0.94,0.037417,1
17,0.004802,0.000930,0.007158,0.001790,11,1,distance,"{'n_neighbors': 11, 'p': 1, 'weights': 'distan...",0.95,0.85,0.9,1.0,0.95,0.93,0.050990,14
18,0.005127,0.000930,0.006390,0.000941,11,2,uniform,"{'n_neighbors': 11, 'p': 2, 'weights': 'uniform'}",0.90,0.90,0.9,1.0,0.95,0.93,0.040000,7
19,0.005573,0.000729,0.006277,0.001694,11,2,distance,"{'n_neighbors': 11, 'p': 2, 'weights': 'distan...",0.90,0.90,0.9,1.0,0.95,0.93,0.040000,7

In [21]:
best_model = grid.best_estimator_
best_model

KNeighborsClassifier(n_neighbors=3, weights='distance')

In [24]:
result_KNN[['param_n_neighbors','param_weights','mean_test_score']]

    param_n_neighbors param_weights  mean_test_score
0                   3       uniform             0.93
1                   3      distance             0.93
2                   3       uniform             0.93
3                   3      distance             0.94
4                   5       uniform             0.92
5                   5      distance             0.92
6                   5       uniform             0.93
7                   5      distance             0.94
8                   7       uniform             0.92
9                   7      distance             0.92
10                  7       uniform             0.93
11                  7      distance             0.94
12                  9       uniform             0.94
13                  9      distance             0.93
14                  9       uniform             0.93
15                  9      distance             0.94
16                 11       uniform             0.94
17                 11      distance             0.93
18                 11       uniform             0.93
19                 11      distance             0.93